# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0002_auto_20170621_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='chore_icon_location',
            field=models.FilePathField(default='Default.png', max_length=255, path='/Users/HOME/Developer/WAC/whatachore/wac/static/wac/styles/images/Icons/cream_icons'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='sub_interval',
            field=models.CharField(choices=[('Random', 'Random'), ('1st', '1st of the month'), ('15th', '15th of the month'), ('Weekday', 'Weekday'), ('Weekend', 'Weekend'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tueday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='random', max_length=15),
        ),
    ]
