# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wac', '0003_assignment_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='week', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
