# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0004_auto_20170720_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='interval',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Every 2 Days', 'Every 2 Days'), ('Every 3 Days', 'Every 3 Days'), ('Weekly', 'Weekly'), ('Every 2 Weeks', 'Every 2 Weeks'), ('Monthly', 'Monthly'), ('Every 2 Months', 'Every 2 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='week', max_length=15),
        ),
    ]
