# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0004_auto_20170516_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
