# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0004_auto_20170519_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
