# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import wac.models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0005_auto_20170516_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.AddField(
            model_name='person',
            name='mugshot',
            field=models.ImageField(blank=True, upload_to=wac.models.Person.get_image_path),
        ),
    ]
