# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 03:30
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0006_auto_20170516_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('mugshot', '500x375', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
