# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0006_auto_20170519_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='chore',
            new_name='what',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='date',
            new_name='when',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wac.Week'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wac.Person'),
        ),
    ]
