# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0007_auto_20170516_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cropping',
        ),
    ]
