# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 13:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0008_remove_person_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='settings.MEDIA_URL')),
        ),
    ]
