# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0009_auto_20170522_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
