# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0010_week_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='weekly_minutes',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
