# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0011_person_weekly_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number_of_chores',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
