# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import wac.models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0011_auto_20170517_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to=wac.models.Person.get_image_path),
        ),
    ]
