# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0012_person_number_of_chores'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dont',
            field=models.BooleanField(default=False),
        ),
    ]
