# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0013_assignment_dont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='dont',
            new_name='done',
        ),
    ]
