# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0014_auto_20170524_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='interval',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Every 2 Days', 'Every 2 Days'), ('Every 3 Days', 'Every 3 Days'), ('Weekly', 'Weekly'), ('Every 2 Weeks', 'Every 2 Weeks'), ('Monthly', 'Monthly'), ('Every 2 Months', 'Every 2 Months'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='week', max_length=15),
        ),
        migrations.AlterField(
            model_name='chore',
            name='sub_interval',
            field=models.CharField(choices=[('None', 'None'), ('Random', 'Random'), ('1st', '1st of the month'), ('15th', '15th of the month'), ('Weekday', 'Weekday'), ('Weekend', 'Weekend'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tueday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='random', max_length=15),
        ),
    ]
