# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wac', '0016_remove_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='day_off',
            field=models.CharField(choices=[('None', 'None'), ('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='None', max_length=15),
        ),
    ]
