# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doNotEmail',
            field=models.BooleanField(default=False),
        ),
    ]
