# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(editable=False, max_length=254, null=True, unique=True),
        ),
    ]
